// Run against `npm run dev` (or explicit Vite port). No login or database writes.
import { spawn } from "node:child_process";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import assert from "node:assert/strict";

const base = process.env.TEST_BASE_URL || "http://127.0.0.1:5185";
const profile = await mkdtemp(join(tmpdir(), "teachlearn-runner-"));
const chrome = spawn(process.env.CHROME_PATH || "C:/Program Files/Google/Chrome/Application/chrome.exe", ["--headless=new", "--disable-gpu", "--no-first-run", "--remote-debugging-port=9338", `--user-data-dir=${profile}`, "about:blank"], { windowsHide: true, stdio: "ignore" });
let ws;
try {
  let targets;
  for (let i = 0; i < 40; i++) { try { targets = await (await fetch("http://127.0.0.1:9338/json")).json(); break; } catch { await new Promise(r => setTimeout(r, 250)); } }
  assert.ok(targets, "Chrome starts");
  ws = new WebSocket(targets.find(t => t.type === "page").webSocketDebuggerUrl);
  await new Promise(r => ws.addEventListener("open", r, { once: true }));
  const pending = new Map(); let id = 0;
  ws.addEventListener("message", e => { const data = JSON.parse(e.data); if (data.id) { const p = pending.get(data.id); pending.delete(data.id); if (data.error) p.reject(data.error); else p.resolve(data.result); } });
  const call = (method, params = {}) => new Promise((resolve, reject) => { const key = ++id; pending.set(key, { resolve, reject }); ws.send(JSON.stringify({ id: key, method, params })); });
  const evaluate = async expression => { const r = await call("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true, replMode: true }); if (r.exceptionDetails) throw new Error(JSON.stringify(r.exceptionDetails)); return r.result.value; };
  const waitFor = async expression => { for (let i = 0; i < 120; i++) { if (await evaluate(expression)) return; await new Promise(r => setTimeout(r, 250)); } throw new Error(`Timed out: ${expression}`); };
  await call("Page.enable");
  await call("Log.enable");
  ws.addEventListener("message", e => { const data = JSON.parse(e.data); if (data.method === "Log.entryAdded" && data.params.entry.level === "error") console.log(data.params.entry.text); });
  await call("Emulation.setDeviceMetricsOverride", { width: 1280, height: 960, deviceScaleFactor: 1, mobile: false });
  await call("Page.navigate", { url: `${base}/about` });
  await waitFor('Boolean(document.querySelector(".about-page"))');
  assert.equal(await evaluate('document.querySelector("h1").textContent'), "About Us");
  await evaluate(`window.runner = await import('/src/components/code/isolatedRunner.js');`);
  const run = (language, code, executionMs = 5000) => evaluate(`await window.runner.runIsolated(${JSON.stringify(language)}, ${JSON.stringify(code)}, () => {}, {executionMs:${executionMs}}).promise`);
  const js = await run("javascript", 'console.log("Hello"); console.log(5+7)');
  assert.equal(js.output, "Hello\n12\n", JSON.stringify(js));
  assert.match((await run("javascript", 'throw new Error("example error")')).error, /example error/);
  assert.equal((await run("javascript", "while(true) {}", 400)).errorCode, "timeout");
  assert.equal((await run("javascript", 'console.log("recovered")')).output, "recovered\n");
  const isolation = await run("javascript", `try { indexedDB.open('firebaseLocalStorageDb'); } catch { console.log('storage blocked'); } try { await fetch('${base}/'); } catch { console.log('network blocked'); } console.log(typeof document);`);
  assert.equal(isolation.output, "storage blocked\nnetwork blocked\nundefined\n");
  assert.equal(await evaluate('document.querySelectorAll("iframe[hidden]").length'), 0);
  console.log("PASS JavaScript output, errors, timeout recovery, storage/network isolation, cleanup");
  const python = await run("python", 'print("Hello!")\nprint(5 + 7)\nprint("مرحبا")');
  assert.equal(python.output, "Hello!\n12\nمرحبا\n", JSON.stringify(python));
  assert.match((await run("python", "print(1/0)")).error, /ZeroDivisionError/);
  assert.equal((await run("python", "while True: pass", 500)).errorCode, "timeout");
  assert.equal((await run("python", "print(12)")).output, "12\n");
  console.log("PASS Python output, Unicode, errors, timeout recovery");
  await evaluate(`
    const React = await import('/node_modules/.vite/deps/react.js');
    const {createRoot} = await import('/node_modules/.vite/deps/react-dom_client.js');
    const {LanguageProvider} = await import('/src/context/LanguageContext.jsx');
    const {default: CodeRunner} = await import('/src/components/code/CodeRunner.jsx');
    window.monaco = await import('/src/components/code/monacoSetup.js');
    document.querySelector('#root').style.display = 'none';
    const node = document.createElement('div'); document.body.append(node);
    window.testRoot = createRoot(node); window.results = [];
    window.mountRunner = config => window.testRoot.render(React.createElement(LanguageProvider, null, React.createElement(CodeRunner, {key: JSON.stringify(config), config, xpReward: 20, onResult: result => window.results.push(result)})));
    window.mountRunner({language:'javascript', starterCode:'console.log(12)', expectedOutput:'12'});
  `);
  await waitFor('Boolean(document.querySelector(".monaco-editor"))');
  await evaluate('document.querySelector(".code-run").click()');
  await waitFor('window.results.length === 1');
  assert.equal(await evaluate('window.results[0].passed'), true);
  await mkdir("artifacts/code-runner", { recursive: true });
  const shot = async name => { await new Promise(r => setTimeout(r, 400)); const r = await call("Page.captureScreenshot", { format: "png", captureBeyondViewport: true }); await writeFile(`artifacts/code-runner/${name}.png`, Buffer.from(r.data, "base64")); };
  await shot("javascript-desktop");
  await evaluate(`document.querySelectorAll('.code-actions button')[1].click()`);
  assert.equal(await evaluate('Boolean(document.querySelector(".code-correct"))'), false);
  await evaluate(`window.mountRunner({language:'web', starterCode:{html:'<h1>Web preview</h1>',css:'h1 {color: purple}',javascript:'document.querySelector("h1").textContent = "Working preview"'}})`);
  await waitFor('Boolean(document.querySelector(".code-tabs"))');
  await evaluate('document.querySelector(".code-run").click()');
  await waitFor('Boolean(document.querySelector(".code-preview iframe"))');
  assert.equal(await evaluate('document.querySelector(".code-preview iframe").getAttribute("sandbox")'), "allow-scripts");
  assert.equal(await evaluate('document.querySelector(".code-preview iframe").contentDocument === null'), true);
  await call("Emulation.setDeviceMetricsOverride", { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await shot("web-mobile");
  assert.equal(await evaluate('document.documentElement.scrollWidth > innerWidth'), false);
  console.log("PASS Monaco rendering, validation, reset, web sandbox, mobile layout; About Us renders");
  await call("Browser.close");
} finally { ws?.close(); chrome.kill(); }
